
apiVersion: v1
kind: Service
metadata:
  name: srv-grpc-server
  namespace: pf-sopes1
spec:
  selector:
    app: grpc-server
  type: ClusterIP
  ports:
  - port: 40000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: pf-sopes1
spec:
  selector:
    matchLabels:
      app: grpc-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: willop/pf_grpc_server_201408419
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: "Sopes1P"
        - name: DB_PORT
          value: "3306"
        - name: DB_PASSWORD
          value: "Sopes1P"
        - name: DB_DATABASE
          value: "proyecto1"     
        - name: CLIENT_HOST
          value: "0.0.0.0"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 40000
          name: grpc-server
