apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: pf-sopes1
  labels:
    app: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer
