apiVersion: v1
kind: Namespace
metadata:
  name: pf-sopes1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: pf-sopes1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: willop/pf_mysql
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        name: mysql
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: pf-sopes1
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3306
      targetPort: 3306
  selector:
    app: mysql




    